// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.3
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================


extern void Timer (
const volatile uint1* PPS,
unsigned int num_clks,
volatile uint1* trigger_out);

