// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.3
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================


#include <systemc>
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <stdint.h>
#include "SysCFileHandler.h"

using namespace std;
using namespace sc_core;
using namespace sc_dt;
// [define_apint] ---------->
// apint = uint1
#define uint1 bool



   #define AUTOTB_TVIN_PPS  "../tv/cdatafile/c.Timer.autotvin_PPS.dat"
   #define AUTOTB_TVIN_num_clks  "../tv/cdatafile/c.Timer.autotvin_num_clks.dat"
   #define AUTOTB_TVOUT_trigger_out  "../tv/cdatafile/c.Timer.autotvout_trigger_out.dat"
   #define INTER_TCL  "../tv/cdatafile/ref.tcl"

   #define AUTOTB_TVOUT_PC_trigger_out  "../tv/rtldatafile/rtl.Timer.autotvout_trigger_out.dat"

class AESL_TRANSACTION {
    public:
        AESL_TRANSACTION(const char* name) {
            mName = (char *)malloc((strlen(name)+1)*sizeof(char));            strcpy(mName,name);
        }
        ~AESL_TRANSACTION() {
            free(mName);        }
    public:
        FILE* mFile;
        char* mName;
};

class INTER_TCL_FILE {
    public:
//functions
        INTER_TCL_FILE(const char* name) {
            mName = name;
            PPS_depth = 0;
            num_clks_depth = 0;
            trigger_out_depth = 0;
            trans_num =0;
        }
        ~INTER_TCL_FILE() {
            mFile.open(mName);
            if (!mFile.good() ) {
                cout<<"Failed to open file ref.tcl."<<endl;
                exit (1);
            }
            string total_list = get_depth_list();
            mFile<<"set depth_list {\n";
            mFile<<total_list; 
            mFile<<"}\n";
            mFile<<"set trans_num "<<trans_num<<endl;
            mFile.close();
        }
        string get_depth_list () {
            stringstream total_list;
            total_list<<"   {PPS "<< PPS_depth << "}\n";
            total_list<<"   {num_clks "<< num_clks_depth << "}\n";
            total_list<<"   {trigger_out "<< trigger_out_depth << "}\n";
            return total_list.str();
        }
        void set_num (int num , int* class_num) {
            (*class_num) = (*class_num) > num ? (*class_num) : num;
        }
    public:
//variables
        int PPS_depth;
        int num_clks_depth;
        int trigger_out_depth;
        int trans_num;
    private:
        ofstream mFile;
        const char* mName;
};

class AESL_TRANSACTION_PC {
    public:
        AESL_TRANSACTION_PC(const char* name) {
            mName = (char *)malloc((strlen(name)+1)*sizeof(char));            strcpy(mName,name);
        }
        ~AESL_TRANSACTION_PC() {
            free(mName);        }
    public:
        fstream file_token;
        char * mName;
};

extern "C" void Timer (
uint1* PPS,
int num_clks,
uint1* trigger_out);
#define Timer AESL_ORIG_DUT_Timer
extern "C" void Timer (
uint1* PPS,
int num_clks,
uint1* trigger_out);
#undef Timer
void Timer (
uint1* PPS,
int num_clks,
uint1* trigger_out) {

    fstream wrapc_switch_file_token;

    wrapc_switch_file_token.open(".hls_cosim_wrapc_switch.log");

    fstream wrapc_tv_switch_file_token;

    wrapc_tv_switch_file_token.open(".hls_cosim_wrapc_tv_switch.log");

    int AESL_i;

    if (wrapc_switch_file_token.good()) {

        static unsigned AESL_transaction_pc;

        string AESL_token;

        string AESL_num;

            FILE * communication_file;

            char get_com_str_set[4];

            char get_com_str[19];

            int get_com_int;

            do {

                do {

                    communication_file = fopen("com_wrapc_pc.tcl","r");

                } while (communication_file == NULL);

                fscanf(communication_file, "%s %s %d", get_com_str_set, get_com_str, &get_com_int);

                fclose(communication_file);

            } while (strcmp(get_com_str, "trans_num_wrapc_pc") != 0 || get_com_int < AESL_transaction_pc);

        static AESL_FILE_HANDLER aesl_fh;

        char str[100];

        char transaction_num_char[40];

        sprintf(transaction_num_char, "_%0d", AESL_transaction_pc);

        strcpy(str,AUTOTB_TVOUT_PC_trigger_out);

        strcat(str,transaction_num_char);

        AESL_TRANSACTION_PC tvout_pc_trigger_out(str);

        tvout_pc_trigger_out.file_token.open(tvout_pc_trigger_out.mName);

        if (!tvout_pc_trigger_out.file_token.good()) {

            cout<<"Failed to open tv file ."<<tvout_pc_trigger_out.mName<<endl;

            exit (1);

        }

        tvout_pc_trigger_out.file_token >> AESL_token;//[[transaction]]

        if ( AESL_token != "[[transaction]]") {

           cout<<"Illegal file tvout_trigger_out format !"<<endl;

           exit(1);

        }

        tvout_pc_trigger_out.file_token >> AESL_num;//transaction number

        if (atoi(AESL_num.c_str()) == AESL_transaction_pc ) {

            tvout_pc_trigger_out.file_token >> AESL_token;//data

            sc_bv<1> *trigger_out_pc_buffer = new sc_bv<1>[1];

            int i = 0;

            while (AESL_token != "[[/transaction]]") {

                bool no_x = false;

                bool err = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('X');

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'trigger_out', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                no_x = false;

                while (!no_x) {

                size_t x_found = AESL_token.find('x', 2);

                if (x_found != string::npos) {

                    if (!err) {

                        cerr << "@W [SIM-201] RTL produces unknown value 'X' on port 'trigger_out', possible cause: There are uninitialized variables in the C design." << endl; 

                        err = true;

                    }

                    AESL_token.replace(x_found, 1, "0");

                } else {

                    no_x = true;

                }

                }

                if (AESL_token != "") {

                    trigger_out_pc_buffer[i] = AESL_token.c_str();

                    i++;

                }

                tvout_pc_trigger_out.file_token >> AESL_token;//data or [[/transaction]]

                if (AESL_token == "[[[/runtime]]]" || tvout_pc_trigger_out.file_token.eof()) {

                   cout<<"Illegal file tvout_trigger_out format !"<<endl;

                   exit(1);

                }

            }

            tvout_pc_trigger_out.file_token.close();

            strcpy(str,AUTOTB_TVOUT_PC_trigger_out);

            strcat(str,transaction_num_char);

            remove(str);

            if (i > 0) {

                sc_lv<1>* trigger_out_lv0_0_0_1 = new sc_lv<1>[1];

                AESL_i = 0;

                for (int i_0 = 0; i_0 <= 0; i_0 += 1)

                {

                if(&(trigger_out[0]) != NULL)

                {

                trigger_out_lv0_0_0_1[0 + AESL_i].range(0, 0) = sc_bv<1>(trigger_out_pc_buffer[0 + AESL_i].range(0, 0));

                }

                AESL_i++;

                }

                AESL_i = 0; //subscript for rtl array

                for (int i_0 = 0; i_0 <= 0 ; i_0+= 1) {

                    if(&(trigger_out[0]) != 0) {

                       trigger_out[i_0] = (trigger_out_lv0_0_0_1[0 + AESL_i]).to_uint64();

                    }

                    AESL_i++;

                }

                }

            delete [] trigger_out_pc_buffer;

        }

        AESL_transaction_pc ++ ;

    } else if (wrapc_tv_switch_file_token.good()){

        static unsigned AESL_transaction;

        char transaction_num_char[40];

        sprintf(transaction_num_char, "_%0d", AESL_transaction);

        char file_name_char[100];

        strcpy(file_name_char, AUTOTB_TVIN_PPS);

        strcat(file_name_char, transaction_num_char);

        AESL_TRANSACTION tvin_PPS(file_name_char);

        strcpy(file_name_char, AUTOTB_TVIN_num_clks);

        strcat(file_name_char, transaction_num_char);

        AESL_TRANSACTION tvin_num_clks(file_name_char);

        strcpy(file_name_char, AUTOTB_TVOUT_trigger_out);

        strcat(file_name_char, transaction_num_char);

        AESL_TRANSACTION tvout_trigger_out(file_name_char);

        int leading_zero;

        tvin_PPS.mFile = fopen(tvin_PPS.mName, "w");

        if (tvin_PPS.mFile == NULL) {

            cout<<"Failed to open tv file ."<<tvin_PPS.mName<<endl;

            exit (1);

        }

        fprintf(tvin_PPS.mFile, "[[transaction]] %d\n", AESL_transaction);

        sc_bv<1> *PPS_tvin_wrapc_buffer = new sc_bv<1>[1];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= 0 ; i_0+= 1) {

        sc_lv<1> PPS_tmp_mem; 

            if(&(PPS[0]) != 0) {

            PPS_tmp_mem = PPS[i_0];

               PPS_tvin_wrapc_buffer[0 + AESL_i].range(0, 0) = PPS_tmp_mem.range(0, 0 ) ;

            }

            AESL_i++;

        }

        for (int i = 0; i < 1 ; i++) {

            fprintf(tvin_PPS.mFile, "%s\n", (PPS_tvin_wrapc_buffer[i]).to_string(SC_HEX).c_str());

        }

        fprintf(tvin_PPS.mFile, "[[/transaction]] \n");

        fclose(tvin_PPS.mFile);

        delete [] PPS_tvin_wrapc_buffer;

        tvin_num_clks.mFile = fopen(tvin_num_clks.mName, "w");

        if (tvin_num_clks.mFile == NULL) {

            cout<<"Failed to open tv file ."<<tvin_num_clks.mName<<endl;

            exit (1);

        }

        fprintf(tvin_num_clks.mFile, "[[transaction]] %d\n", AESL_transaction);

        sc_bv<32> num_clks_tvin_wrapc_buffer;

        AESL_i = 0; //subscript for rtl array

        sc_lv<32> num_clks_tmp_mem; 

        if(&(num_clks) != 0) {

        num_clks_tmp_mem = num_clks;

           num_clks_tvin_wrapc_buffer.range(31, 0) = num_clks_tmp_mem.range(31, 0 ) ;

        }

        AESL_i++;

        for (int i = 0; i < 1 ; i++) {

            fprintf(tvin_num_clks.mFile, "%s\n", (num_clks_tvin_wrapc_buffer).to_string(SC_HEX).c_str());

        }

        fprintf(tvin_num_clks.mFile, "[[/transaction]] \n");

        fclose(tvin_num_clks.mFile);

        AESL_ORIG_DUT_Timer(PPS,num_clks,trigger_out);

        tvout_trigger_out.mFile = fopen(tvout_trigger_out.mName, "w");

        if (tvout_trigger_out.mFile == NULL) {

            cout<<"Failed to open tv file ."<<tvout_trigger_out.mName<<endl;

            exit (1);

        }

        fprintf(tvout_trigger_out.mFile, "[[transaction]] %d\n", AESL_transaction);

        sc_bv<1> *trigger_out_tvout_wrapc_buffer = new sc_bv<1>[1];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= 0 ; i_0+= 1) {

        sc_lv<1> trigger_out_tmp_mem; 

            if(&(trigger_out[0]) != 0) {

            trigger_out_tmp_mem = trigger_out[i_0];

               trigger_out_tvout_wrapc_buffer[0 + AESL_i].range(0, 0) = trigger_out_tmp_mem.range(0, 0 ) ;

            }

            AESL_i++;

        }

        for (int i = 0; i < 1 ; i++) {

            fprintf(tvout_trigger_out.mFile, "%s\n", (trigger_out_tvout_wrapc_buffer[i]).to_string(SC_HEX).c_str());

        }

        fprintf(tvout_trigger_out.mFile, "[[/transaction]] \n");

        fclose(tvout_trigger_out.mFile);

        delete [] trigger_out_tvout_wrapc_buffer;
        FILE* communication_file;
        do {
            communication_file = fopen("com_wrapc.tcl", "w");
        } while (communication_file == NULL);
        fprintf(communication_file, "set trans_num_wrapc %d \n\n", AESL_transaction);
        fclose(communication_file);
    if(AESL_transaction > 0) {
        FILE * communication_file;
        char get_com_str_set[4];
        char get_com_str[14];
        int get_com_int;
        do {
            do {
                communication_file = fopen("com_rtl_ready.tcl","r");
            } while (communication_file == NULL);
            fscanf(communication_file, "%s %s %d", get_com_str_set, get_com_str, &get_com_int);
            fclose(communication_file);
        } while (strcmp(get_com_str, "trans_num_rtl") != 0 || get_com_int < AESL_transaction);
    }

        if(AESL_transaction > 0) {

        sprintf(transaction_num_char, "_%0d", AESL_transaction - 1);

        strcpy(file_name_char, AUTOTB_TVIN_PPS);

        strcat(file_name_char, transaction_num_char);

        remove(file_name_char);

        strcpy(file_name_char, AUTOTB_TVIN_num_clks);

        strcat(file_name_char, transaction_num_char);

        remove(file_name_char);

        strcpy(file_name_char, AUTOTB_TVOUT_trigger_out);

        strcat(file_name_char, transaction_num_char);

        remove(file_name_char);
}

        AESL_transaction++;

    } else {

        static unsigned AESL_transaction;

        static AESL_FILE_HANDLER aesl_fh;

        static INTER_TCL_FILE tcl_file(INTER_TCL);


        int leading_zero;

        sc_bv<1> *PPS_tvin_wrapc_buffer = new sc_bv<1>[1];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= 0 ; i_0+= 1) {

        sc_lv<1> PPS_tmp_mem; 

            if(&(PPS[0]) != 0) {

            PPS_tmp_mem = PPS[i_0];

               PPS_tvin_wrapc_buffer[0 + AESL_i].range(0, 0) = PPS_tmp_mem.range(0, 0 ) ;

            }

            AESL_i++;

        }

        tcl_file.set_num(1,&tcl_file.PPS_depth);

        delete [] PPS_tvin_wrapc_buffer;

        sc_bv<32> num_clks_tvin_wrapc_buffer;

        AESL_i = 0; //subscript for rtl array

        sc_lv<32> num_clks_tmp_mem; 

        if(&(num_clks) != 0) {

        num_clks_tmp_mem = num_clks;

           num_clks_tvin_wrapc_buffer.range(31, 0) = num_clks_tmp_mem.range(31, 0 ) ;

        }

        AESL_i++;

        tcl_file.set_num(1,&tcl_file.num_clks_depth);

        AESL_ORIG_DUT_Timer(PPS,num_clks,trigger_out);

        sc_bv<1> *trigger_out_tvout_wrapc_buffer = new sc_bv<1>[1];

        AESL_i = 0; //subscript for rtl array

        for (int i_0 = 0; i_0 <= 0 ; i_0+= 1) {

        sc_lv<1> trigger_out_tmp_mem; 

            if(&(trigger_out[0]) != 0) {

            trigger_out_tmp_mem = trigger_out[i_0];

               trigger_out_tvout_wrapc_buffer[0 + AESL_i].range(0, 0) = trigger_out_tmp_mem.range(0, 0 ) ;

            }

            AESL_i++;

        }

        tcl_file.set_num(1,&tcl_file.trigger_out_depth);

        delete [] trigger_out_tvout_wrapc_buffer;

        AESL_transaction++;

        tcl_file.set_num(AESL_transaction , &tcl_file.trans_num);

    }
}


// apint = uint1
#undef uint1
