#pragma line 1 "Timer.c" ::: 0
#pragma line 1 "Timer.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 283 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 6 "<command line>" 2 ::: 190
#pragma line 1 "<built-in>" 2 ::: 191
#pragma line 1 "Timer.c" 2 ::: 192
#pragma line 1 "./Timer.h" 1 ::: 196
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 1 ::: 201
#pragma line 62 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" ::: 254
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 255
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 281
#pragma line 128 "/usr/include/features.h" 3 4 ::: 382
#pragma line 149 "/usr/include/features.h" 3 4 ::: 396
#pragma line 177 "/usr/include/features.h" 3 4 ::: 398
#pragma line 193 "/usr/include/features.h" 3 4 ::: 401
#pragma line 350 "/usr/include/features.h" 3 4 ::: 432
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 436
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 471
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 477
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 500
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 541
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 547
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 565
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 571
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 575
#pragma line 148 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 577
#pragma line 166 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 581
#pragma line 193 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 591
#pragma line 253 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 644
#pragma line 306 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 685
#pragma line 339 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 706
#pragma line 385 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 730
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 731
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 733
#pragma line 386 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 735
#pragma line 375 "/usr/include/features.h" 2 3 4 ::: 736
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 761
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 772
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 777
#pragma line 399 "/usr/include/features.h" 2 3 4 ::: 778
#pragma line 26 "/usr/include/string.h" 2 3 4 ::: 779
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 787
#pragma line 56 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 828
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 831
#pragma line 96 "/usr/include/string.h" 3 4 ::: 872
#pragma line 128 "/usr/include/string.h" 3 4 ::: 875
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 912
#pragma line 164 "/usr/include/string.h" 2 3 4 ::: 955
#pragma line 212 "/usr/include/string.h" 3 4 ::: 978
#pragma line 236 "/usr/include/string.h" 3 4 ::: 980
#pragma line 263 "/usr/include/string.h" 3 4 ::: 985
#pragma line 283 "/usr/include/string.h" 3 4 ::: 988
#pragma line 315 "/usr/include/string.h" 3 4 ::: 998
#pragma line 342 "/usr/include/string.h" 3 4 ::: 1003
#pragma line 398 "/usr/include/string.h" 3 4 ::: 1024
#pragma line 444 "/usr/include/string.h" 3 4 ::: 1055
#pragma line 489 "/usr/include/string.h" 3 4 ::: 1078
#pragma line 517 "/usr/include/string.h" 3 4 ::: 1084
#pragma line 555 "/usr/include/string.h" 3 4 ::: 1108
#pragma line 63 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 2 ::: 1134
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 1135
#pragma line 33 "/usr/include/stdio.h" 3 4 ::: 1157
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1158
#pragma line 56 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1183
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 1186
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 1188
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1216
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1218
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1220
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 1281
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 1288
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1306
#pragma line 76 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1311
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1322
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 1391
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1405
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1408
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1409
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1441
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1457
#pragma line 56 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1482
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1485
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1490
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1512
#pragma line 897 "/usr/include/wchar.h" 3 4 ::: 1533
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1536
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1547
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1557
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1559
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1563
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1612
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1613
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1619
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1621
#pragma line 177 "/usr/include/libio.h" 3 4 ::: 1645
#pragma line 245 "/usr/include/libio.h" 3 4 ::: 1656
#pragma line 293 "/usr/include/libio.h" 3 4 ::: 1697
#pragma line 302 "/usr/include/libio.h" 3 4 ::: 1699
#pragma line 334 "/usr/include/libio.h" 3 4 ::: 1721
#pragma line 390 "/usr/include/libio.h" 3 4 ::: 1747
#pragma line 434 "/usr/include/libio.h" 3 4 ::: 1751
#pragma line 464 "/usr/include/libio.h" 3 4 ::: 1766
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1778
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1784
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1786
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1796
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1818
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1834
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1851
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1883
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1929
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1943
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1946
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 2022
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 2061
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 2102
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 2215
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 2278
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 2327
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 2338
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2368
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2396
#pragma line 910 "/usr/include/stdio.h" 3 4 ::: 2429
#pragma line 931 "/usr/include/stdio.h" 3 4 ::: 2441
#pragma line 64 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 2 ::: 2444
#pragma line 77 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" ::: 2445
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" 1 ::: 2446
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 1 ::: 2504
#pragma line 97 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 2558
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 2559
#pragma line 98 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 3598
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 3599
#pragma line 99 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 4626
#pragma line 108 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 4627
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 4628
#pragma line 109 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 5667
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 5668
#pragma line 110 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 6695
#pragma line 131 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 6696
#pragma line 58 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 6699
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" 1 ::: 6700
#pragma line 98 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6753
#pragma line 108 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6755
#pragma line 129 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6757
#pragma line 143 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6762
#pragma line 156 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6765
#pragma line 192 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6767
#pragma line 59 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 6769
#pragma line 85 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" ::: 6770
#pragma line 78 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 2 ::: 6772
#pragma line 6 "./Timer.h" 2 ::: 6773
#pragma line 4 "Timer.c" 2 ::: 6796
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_utils.h" 1 ::: 6797
#pragma line 73 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_utils.h" ::: 6850
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 6851
#pragma line 74 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_utils.h" 2 ::: 6981
#pragma line 5 "Timer.c" 2 ::: 6982
