#pragma line 1 "Timer.c" ::: -10
#pragma line 1 "Timer.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 283 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 6 "<command line>" 2 ::: 180
#pragma line 1 "<built-in>" 2 ::: 181
#pragma line 1 "Timer.c" 2 ::: 182
#pragma line 1 "./Timer.h" 1 ::: 186
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 1 ::: 191
#pragma line 62 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" ::: 244
#pragma line 1 "/usr/include/string.h" 1 3 4 ::: 245
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 271
#pragma line 128 "/usr/include/features.h" 3 4 ::: 372
#pragma line 149 "/usr/include/features.h" 3 4 ::: 386
#pragma line 177 "/usr/include/features.h" 3 4 ::: 388
#pragma line 193 "/usr/include/features.h" 3 4 ::: 391
#pragma line 350 "/usr/include/features.h" 3 4 ::: 422
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 426
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 461
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 467
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 490
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 531
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 537
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 555
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 561
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 565
#pragma line 148 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 567
#pragma line 166 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 571
#pragma line 193 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 581
#pragma line 253 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 634
#pragma line 306 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 675
#pragma line 339 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 696
#pragma line 385 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 720
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 721
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 723
#pragma line 386 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 725
#pragma line 375 "/usr/include/features.h" 2 3 4 ::: 726
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 751
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 762
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 767
#pragma line 399 "/usr/include/features.h" 2 3 4 ::: 768
#pragma line 26 "/usr/include/string.h" 2 3 4 ::: 769
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 777
#pragma line 56 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 818
#pragma line 33 "/usr/include/string.h" 2 3 4 ::: 821
#pragma line 96 "/usr/include/string.h" 3 4 ::: 862
#pragma line 128 "/usr/include/string.h" 3 4 ::: 865
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 902
#pragma line 164 "/usr/include/string.h" 2 3 4 ::: 945
#pragma line 212 "/usr/include/string.h" 3 4 ::: 968
#pragma line 236 "/usr/include/string.h" 3 4 ::: 970
#pragma line 263 "/usr/include/string.h" 3 4 ::: 975
#pragma line 283 "/usr/include/string.h" 3 4 ::: 978
#pragma line 315 "/usr/include/string.h" 3 4 ::: 988
#pragma line 342 "/usr/include/string.h" 3 4 ::: 993
#pragma line 398 "/usr/include/string.h" 3 4 ::: 1014
#pragma line 444 "/usr/include/string.h" 3 4 ::: 1045
#pragma line 489 "/usr/include/string.h" 3 4 ::: 1068
#pragma line 517 "/usr/include/string.h" 3 4 ::: 1074
#pragma line 555 "/usr/include/string.h" 3 4 ::: 1098
#pragma line 63 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 2 ::: 1124
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 1125
#pragma line 33 "/usr/include/stdio.h" 3 4 ::: 1147
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1148
#pragma line 56 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1173
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 1176
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 1178
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 1206
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 1208
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1210
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 1271
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 1278
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1296
#pragma line 76 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 1301
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 1312
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 1381
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1395
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1398
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1399
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1431
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1447
#pragma line 56 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1472
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1475
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1480
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1502
#pragma line 897 "/usr/include/wchar.h" 3 4 ::: 1523
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1526
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1537
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1547
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1549
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1553
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1602
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1603
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1609
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1611
#pragma line 177 "/usr/include/libio.h" 3 4 ::: 1635
#pragma line 245 "/usr/include/libio.h" 3 4 ::: 1646
#pragma line 293 "/usr/include/libio.h" 3 4 ::: 1687
#pragma line 302 "/usr/include/libio.h" 3 4 ::: 1689
#pragma line 334 "/usr/include/libio.h" 3 4 ::: 1711
#pragma line 390 "/usr/include/libio.h" 3 4 ::: 1737
#pragma line 434 "/usr/include/libio.h" 3 4 ::: 1741
#pragma line 464 "/usr/include/libio.h" 3 4 ::: 1756
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1768
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1774
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1776
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1786
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1808
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1824
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1841
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1873
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1919
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1933
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1936
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 2012
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 2051
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 2092
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 2205
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 2268
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 2317
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 2328
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2358
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2386
#pragma line 910 "/usr/include/stdio.h" 3 4 ::: 2419
#pragma line 931 "/usr/include/stdio.h" 3 4 ::: 2431
#pragma line 64 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 2 ::: 2434
#pragma line 77 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" ::: 2435
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" 1 ::: 2436
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 1 ::: 2494
#pragma line 97 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 2548
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 2549
#pragma line 98 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 3588
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 3589
#pragma line 99 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 4616
#pragma line 108 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 4617
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.def" 1 ::: 4618
#pragma line 109 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 5657
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt_ext.def" 1 ::: 5658
#pragma line 110 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" 2 ::: 6685
#pragma line 131 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_dt.h" ::: 6686
#pragma line 58 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 6689
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" 1 ::: 6690
#pragma line 98 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6743
#pragma line 108 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6745
#pragma line 129 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6747
#pragma line 143 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6752
#pragma line 156 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6755
#pragma line 192 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_ssdm_bits.h" ::: 6757
#pragma line 59 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" 2 ::: 6759
#pragma line 85 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_apint.h" ::: 6760
#pragma line 78 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_cint.h" 2 ::: 6762
#pragma line 6 "./Timer.h" 2 ::: 6763
#pragma line 4 "Timer.c" 2 ::: 6786
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_utils.h" 1 ::: 6787
#pragma line 73 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_utils.h" ::: 6840
#pragma line 1 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 6841
#pragma line 74 "/media/imranqureshi/40edadaa-013a-44ac-bdd0-e7787032b2e2/xilinx/Vivado_HLS/2015.3/common/technology/autopilot/ap_utils.h" 2 ::: 6971
#pragma line 5 "Timer.c" 2 ::: 6972
